### ISSUE TITLE
不是很会JAVA

### ISSUE THREAD

**Issue by ShikinZhang** [BQsummer/pubg_recoil#1]
不是很会java的东西，

尝试过下eclipse，然后弄个fatjar，然后新建一个工程，把mousehook.java添加进去，然后打包成fatjar，然后把2个dll复制到fatjar同一个目录下，cmd运行然后报错

PS D:\hehe> cd .\pubg_recoil-master\
PS D:\hehe\pubg_recoil-master> cd .\combine\
PS D:\hehe\pubg_recoil-master\combine> java -jar .\combine_fat.jar
Exception in thread "main" java.lang.ClassNotFoundException: MouseHook
        at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:602)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:300)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
PS D:\hehe\pubg_recoil-master\combine>

**Comment by yanzhi008** [comment]
编译出来的包有问题 找不到MouseHook 类

**Comment by NatsumeZhang** [comment]
打包参数有问题的
